import os
import io
import json
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.colors import HexColor, white, black
from reportlab.lib.units import cm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.enums import TA_CENTER, TA_LEFT


DARK_BG  = HexColor("#0D1117")
CYAN     = HexColor("#00FFD1")
LIGHT    = HexColor("#E6EDF3")
MID_GREY = HexColor("#8B949E")
RED      = HexColor("#FF4444")
AMBER    = HexColor("#FFA500")
GREEN    = HexColor("#00CC88")


def generate_report_pdf(report_data: dict, acoustic_features: dict, user_name: str = "Patient") -> bytes:
    """
    Generate a pre-consultation PDF report.
    Returns raw PDF bytes.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=2*cm, rightMargin=2*cm,
        topMargin=2*cm, bottomMargin=2*cm,
    )

    styles   = getSampleStyleSheet()
    title_st = ParagraphStyle("Title", fontSize=20, textColor=CYAN, spaceAfter=6, fontName="Helvetica-Bold")
    h2_st    = ParagraphStyle("H2",    fontSize=13, textColor=CYAN, spaceAfter=4, fontName="Helvetica-Bold")
    body_st  = ParagraphStyle("Body",  fontSize=10, textColor=LIGHT, spaceAfter=3, fontName="Helvetica", leading=14)
    meta_st  = ParagraphStyle("Meta",  fontSize=9,  textColor=MID_GREY, spaceAfter=2, fontName="Helvetica")

    urgency_color = {
        "routine": GREEN,
        "soon":    AMBER,
        "urgent":  RED,
    }.get(report_data.get("urgency", "routine"), MID_GREY)

    story = []

    # Header
    story.append(Paragraph("🩺 Vocal Vitals — Pre-Consultation Report", title_st))
    story.append(Paragraph(f"Patient: {user_name}  |  Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}", meta_st))
    story.append(HRFlowable(width="100%", thickness=1, color=CYAN, spaceAfter=10))

    # Urgency badge
    urgency = report_data.get("urgency", "routine").upper()
    story.append(Paragraph(f"Urgency: <font color='#{urgency_color.hexval()[2:]}''>{urgency}</font>", h2_st))
    story.append(Spacer(1, 6))

    # Chief Complaint
    story.append(Paragraph("Chief Complaint", h2_st))
    story.append(Paragraph(report_data.get("chief_complaint", "N/A"), body_st))
    story.append(Spacer(1, 8))

    # Symptom Timeline
    story.append(Paragraph("Symptom Timeline", h2_st))
    for item in report_data.get("timeline", []):
        story.append(Paragraph(f"• {item}", body_st))
    story.append(Spacer(1, 8))

    # Acoustic Indicators
    story.append(Paragraph("Acoustic Indicators Detected", h2_st))
    for item in report_data.get("acoustic_indicators", []):
        story.append(Paragraph(f"• {item}", body_st))
    story.append(Spacer(1, 8))

    # Acoustic Feature Table
    story.append(Paragraph("Raw Acoustic Features", h2_st))
    feat_data = [["Feature", "Value"]]
    display_keys = {
        "pitch_mean": "Pitch Mean (Hz)",
        "pitch_std":  "Pitch Std Dev (Hz)",
        "jitter":     "Jitter (%)",
        "shimmer":    "Shimmer (%)",
        "hnr":        "HNR (dB)",
        "speech_rate":"Speech Rate (words/s)",
        "pause_freq": "Pause Frequency",
        "breathiness":"Breathiness (0-1)",
    }
    for key, label in display_keys.items():
        val = acoustic_features.get(key, "N/A")
        feat_data.append([label, str(val)])

    tbl = Table(feat_data, colWidths=[10*cm, 5*cm])
    tbl.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (-1,0), CYAN),
        ("TEXTCOLOR",  (0,0), (-1,0), black),
        ("FONTNAME",   (0,0), (-1,0), "Helvetica-Bold"),
        ("FONTSIZE",   (0,0), (-1,-1), 9),
        ("TEXTCOLOR",  (0,1), (-1,-1), LIGHT),
        ("BACKGROUND", (0,1), (-1,-1), HexColor("#161B22")),
        ("ROWBACKGROUNDS", (0,1), (-1,-1), [HexColor("#161B22"), HexColor("#0D1117")]),
        ("GRID",       (0,0), (-1,-1), 0.5, MID_GREY),
        ("PADDING",    (0,0), (-1,-1), 6),
    ]))
    story.append(tbl)
    story.append(Spacer(1, 12))

    # Recommended Specialist
    story.append(Paragraph("Recommended Specialist", h2_st))
    story.append(Paragraph(report_data.get("specialist", "General Practitioner"), body_st))
    story.append(Spacer(1, 8))

    # Full Note
    story.append(Paragraph("Full Clinical Note", h2_st))
    story.append(HRFlowable(width="100%", thickness=0.5, color=MID_GREY))
    story.append(Spacer(1, 4))
    full_note = report_data.get("full_note", "").replace("\n", "<br/>")
    story.append(Paragraph(full_note, body_st))
    story.append(Spacer(1, 12))

    # Disclaimer
    story.append(HRFlowable(width="100%", thickness=0.5, color=MID_GREY))
    story.append(Spacer(1, 4))
    story.append(Paragraph(
        "⚠ This report is generated by an AI screening tool and does NOT constitute a medical diagnosis. "
        "Always consult a qualified healthcare professional.",
        ParagraphStyle("Disclaimer", fontSize=8, textColor=MID_GREY, fontName="Helvetica-Oblique")
    ))

    doc.build(story)
    return buffer.getvalue()
